mvrt-115/MVRT_Site

- app/_data/alumni.yml
- app/_scss/_people.scss
- app/about/alumni.md
- app/about/people.html
There may be typos though, and it is missing class of 2014.
> add alumni page

- app/_scss/_content.scss
- app/_scss/_hero.scss
- app/blog/index.html
- app/join/index.html
Change the hero size from 67vh to 50vh because 67vh is overpowering.
> Make hero smaller

- Gemfile
- Gemfile.lock
Not sure what to do with Gemfile.lock though. Best practices say to check into source control, though.
The important here is that is now uses https. Never noticed that before.
> update deps, use https in Gemfile

- app/_data/coders.yml
- app/humans.txt
http://humanstxt.org/
Just for fun. Add anyone/anything that should go in there.
> add something interesting to humans.txt

- _config.yml
- app/_drafts/kickoff-day-is-tomorrow.md
- app/_drafts/parent-update-x.md
- app/_includes/feed.html
- app/_layouts/post.html
- app/_scss/_blog.scss
- app/_scss/_post.scss
- app/_scss/main.scss
- app/blog/feed.xml
- app/blog/index.html
- app/media/publicity/1999article.md
- app/media/publicity/2001article.md
- app/media/publicity/2006article.md
- app/media/publicity/2007article.md
- app/media/publicity/2009article.md
- app/media/publicity/2010article.md
- app/media/publicity/2011article.md
This PR ~~introduces a simple blog for blogging. Any thoughts?~~ now fixes up the styling of the private blog.
By the way anything in _drafts is just for testing, it won't be included on build.
> blog styling

- app/_data/animations.yml
- app/media/animations.html
also, should we credit siddharth in the humans.txt for #22?
> add animations

- gulpfile.js
> recomplile when any sass file is changed

- app/_data/officers.yml
VP -> Vice President
"Director" placed in front of position names (for most others)
> change the position names

- app/_scss/_document.scss
- app/js/document.js
- app/js/index.js
- app/resources/documents.md
- app/resources/videos.md
- bower.json
- gulpfile.js
- package.json
This change makes the document nav stuck to the top when scrolling
through the entire page, and when clicking on a link, it scrolls to that
section. (However permalink functionality in this way is disabled.)
> add sticky document nav + highlight active section

- app/js/index.js
- app/js/redirect.js
not sure if this is necessary though, as i doubt anyone would have
bookmarked the links
> redirect paths from old website to new paths

- app/_includes/footer.html
- app/about/first.md
- app/about/index.html
- app/about/overview.md
* use original FIRST page content
* there is a separate "page" About FIRST (and permalink)
* the footer links related to first link to something
> improve the content of the "About FIRST" page

- app/_data/officers.yml
> i think we overlooked something very important (regarding names)

- app/js/document.js
> document nav should not overflow footer now

- app/_data/mentors.yml
- app/_scss/_people.scss
- app/about/mentors.html
- app/about/people.html
may want to hold this off for a while, check for typos, get pictures, maybe just use a list of mentors instead
> Add more mentors

- app/_scss/base/_typography.scss
- app/media/animations.html
* make video containers larger
* do not show related videos after playing video
However the YouTube video titles should be changed, and we are missing
2013's animation.
> slightly improve animation page layout

- app/_posts/2015-01-19-test.md
> Test onto develop

- app/_posts/2015-01-19-build-day-16.md
> Build Day 16 onto develop

- app/_posts/2015-01-19-build-day-16.md
> Build Day 16 onto master

- app/about/history/team.html
so officers and drivers content won't get put into the awards list
> add an </ul> on team history page

- app/_data/alumni.yml
- app/_data/history/robots.yml
- app/_data/mentors.yml
- app/humans.txt
> Updates 20150120

- app/_posts/2015-01-25-build-day-17.md
> Build Day 17 onto master

- app/_posts/2015-01-25-build-day-18.md
> Build Day 18 onto develop

- app/_posts/2015-01-25-build-day-18.md
> Build Day 18 onto master

- app/_posts/2015-01-25-build-day-19.md
> Build Day 19 onto master

- app/_posts/2015-01-25-build-day-19.md
> Build Day 19 onto develop

- app/_layouts/post.html
- app/resources/documents.md
- app/resources/submissions/2004wfa.md
- app/resources/submissions/2006chairmans.md
- app/resources/submissions/2007wfa.md
- app/resources/submissions/2009chairmans.md
- app/resources/submissions/2010chairmans.md
- app/resources/submissions/2010wfa.md
* no pictures yet though
* tweaked post layout by a bit
> add Chairman's and WFA submissions

- app/_posts/2015-02-03-blog-2215.md
> Blog-2/2/15 onto develop

- app/_posts/2015-02-03-blog-2215.md
> Blog-2/2/15 onto master

- app/_posts/2015-02-04-blog-entry-for-february-3rd-2015.md
> Blog Entry for February 3rd 2015 onto develop

- app/_posts/2015-02-04-blog-entry-for-february-3rd-2015.md
> Blog Entry for February 3rd 2015 onto master

- app/_posts/2015-02-06-blog-for-2515.md
> Blog for 2/5/15 onto master

- app/_posts/2015-02-06-blog-for-2515.md
> Blog for 2/5/15 onto develop

- app/_posts/2015-02-08-build-2715.md
> Build 2/7/15 onto develop

- app/_posts/2015-02-08-build-2715.md
> Build 2/7/15 onto master

- app/_includes/footer.html
See #57
This just rebases onto develop.
> copyright "year" = {{ site.date | date: '%Y' }}

- app/js/blog.js
- package.json
#80 
Only diff is that it is rebased onto develop.
> actually use the right timezone in the blog

- app/index.html
> add gofundme campaign

- app/index.html
Reverts mvrt-115/MVRT_Site#101
> Revert "add gofundme campaign"

- app/resources/index.html
> Resources Page Updated

- app/headstart/index.html
Can you look through this @akalari. I just want the text to be updated. Thanks!
> Add information about parent night on Headstart page

- .travis.yml
- package.json
Remove call to gulp from package.json, and update travis,yml script to only call gulp
> Node/Travis Updates
